[generate dump]Added error message when saisdkdump fails (#2356)
- What I did
Added error message when saisdkdump fails and cont to gather the rest. This is done to provide more readable information to the user when it cannot be avaialble (syncd for example is not running, during restart, etc).

- How I did it
Checked error code and print log

- How to verify it
Simulate saisdkdump error and verify the console output.

diff --git a/scripts/generate_dump b/scripts/generate_dump
--- a/scripts/generate_dump
+++ b/scripts/generate_dump
@@ -885,6 +885,10 @@ collect_mellanox() {
     ${CMD_PREFIX}docker exec syncd mkdir -p $sai_dump_folder
     ${CMD_PREFIX}docker exec syncd saisdkdump -f $sai_dump_filename
 
+    if [ $? != 0 ]; then
+        echo "Failed to collect saisdkdump."
+    fi
+
     copy_from_docker syncd $sai_dump_folder $sai_dump_folder
     echo "$sai_dump_folder"
     for file in `ls $sai_dump_folder`; do
