Add support for reboot cause and 'show reboot-cause' command for display (#271)

diff --git a/scripts/reboot b/scripts/reboot
--- a/scripts/reboot
+++ b/scripts/reboot
@@ -1,11 +1,11 @@
 #! /bin/bash
 
-# Check root privileges
-if [[ "$EUID" -ne 0 ]]
-then
-  echo "Please run as root" >&2
-  exit 1
-fi
+REBOOT_USER=$(logname)
+REBOOT_TIME=$(date)
+PLATFORM=$(sonic-cfggen -H -v DEVICE_METADATA.localhost.platform)
+DEVPATH="/usr/share/sonic/device"
+PLAT_REBOOT="platform_reboot"
+REBOOT_CAUSE_FILE="/var/cache/sonic/reboot-cause.txt"
 
 function stop_sonic_services()
 {
@@ -14,21 +14,31 @@ function stop_sonic_services()
     sleep 3
 }
 
-# Obtain our platform as we will mount directories with these names in each docker
-PLATFORM=`sonic-cfggen -H -v DEVICE_METADATA.localhost.platform`
 
-DEVPATH="/usr/share/sonic/device"
-REBOOT="platform_reboot"
-
-# Stop syncd gracefully.
-stop_sonic_services
-
-if [ -x ${DEVPATH}/${PLATFORM}/${REBOOT} ]; then
-    sync
-    sleep 3
-    echo "Rebooting with platform ${PLATFORM} specific tool ..."
-    ${DEVPATH}/${PLATFORM}/${REBOOT}
-    exit 0
+# Exit if not superuser
+if [[ "$EUID" -ne 0 ]]; then
+    echo "This command must be run as root" >&2
+    exit 1
 fi
 
-/sbin/reboot $@
+# Stop SONiC services gracefully.
+stop_sonic_services
+
+# Update the reboot cause file to reflect that user issued 'reboot' command
+# Upon next boot, the contents of this file will be used to determine the
+# cause of the previous reboot
+echo "User issued 'reboot' command [User: ${REBOOT_USER}, Time: ${REBOOT_TIME}]" > ${REBOOT_CAUSE_FILE}
+sync
+sleep 3
+
+if [ -x ${DEVPATH}/${PLATFORM}/${PLAT_REBOOT} ]; then
+    echo "Rebooting with platform ${PLATFORM} specific tool ..."
+    exec ${DEVPATH}/${PLATFORM}/${PLAT_REBOOT}
+else
+    # If no platform-specific reboot tool, just run /sbin/reboot
+    exec /sbin/reboot $@
+fi
+
+# Should never reach here
+echo "Reboot failed!" >&2
+exit 1
